import {
  Component,
  HostListener,
  OnInit,
  AfterViewInit,
  ViewEncapsulation,
  ViewChildren,
  ElementRef,
  QueryList
} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  trigger,
  style,
  animate,
  transition,
  query,
  stagger,
} from '@angular/animations';

@Component({
  selector: 'app-landing',
  standalone: true,
  imports: [
    CommonModule
  ],
  templateUrl: './landing.component.html',
  styleUrl: './landing.component.scss',
  encapsulation: ViewEncapsulation.None,
  animations: [
    trigger('fadeSlideUp', [
      transition(':enter', [
        style({ opacity: 0, transform: 'translateY(30px)' }),
        animate(
          '0.6s cubic-bezier(0.16, 1, 0.3, 1)',
          style({ opacity: 1, transform: 'translateY(0)' }),
        ),
      ]),
    ]),
    trigger('staggerContainer', [
      transition(':enter', [
        query(
          '@fadeSlideUp',
          [
            style({ opacity: 0, transform: 'translateY(30px)' }),
            stagger('100ms', [
              animate(
                '0.6s cubic-bezier(0.16, 1, 0.3, 1)',
                style({ opacity: 1, transform: 'translateY(0)' }),
              ),
            ]),
          ],
          { optional: true },
        ),
      ]),
    ]),
  ],
})
export class LandingComponent implements OnInit, AfterViewInit {
  isScrolled = false;
  isMobileMenuOpen = false;
  activeFaqIndex: number | null = null;
  activeSection = 'home';
  sections = ['home', 'features', 'solutions', 'about', 'contact'];

  @ViewChildren('navItem') navItems!: QueryList<ElementRef>;
  indicatorStyle: any = { left: '0px', width: '0px', opacity: 0 };

  // Icons (removed for fallback)

  // Features Data
  features = [
    {
      title: 'Construction Planning',
      description:
        'Intelligent scheduling and resource allocation powered by predictive AI models.',
      icon: 'Building',
    },
    {
      title: 'Site Monitoring',
      description:
        'Real-time 360-degree site visibility with automated progress tracking and reporting.',
      icon: 'Activity',
    },
    {
      title: 'Employee Management',
      description:
        'Seamless workforce coordination, attendance tracking, and compliance management.',
      icon: 'Users',
    },
    {
      title: 'Material Tracking',
      description:
        'End-to-end supply chain visibility from procurement to on-site utilization.',
      icon: 'CheckCircle',
    },
    {
      title: 'Analytics',
      description:
        'Enterprise-grade dashboards delivering actionable insights and financial forecasting.',
      icon: 'LineChart',
    },
    {
      title: 'AI Reports',
      description:
        'Automated daily logs and safety compliance reports generated by advanced AI.',
      icon: 'Cpu',
    },
  ];

  // Carousel Images
  carouselImages = [
    'https://images.unsplash.com/photo-1541888081622-1d57718e2be2?auto=format&fit=crop&q=80&w=1600&h=900',
    'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&q=80&w=1600&h=900',
    'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=1600&h=900',
    'https://images.unsplash.com/photo-1504307651254-35680f356f58?auto=format&fit=crop&q=80&w=1600&h=900',
  ];

  // Counters
  stats = [
    { label: 'Organizations', value: 500, suffix: '+' },
    { label: 'Users', value: 10000, suffix: '+' },
    { label: 'Projects', value: 120, suffix: '+' },
    { label: 'Customer Satisfaction', value: 95, suffix: '%' },
  ];

  @HostListener('window:scroll', [])
  onWindowScroll() {
    this.isScrolled = window.scrollY > 50;

    let currentSection = 'home';
    for (const section of this.sections) {
      const element = document.getElementById(section);
      if (element) {
        const rect = element.getBoundingClientRect();
        if (rect.top <= 250) {
          currentSection = section;
        }
      }
    }
    
    if (this.activeSection !== currentSection) {
      this.activeSection = currentSection;
      this.updateIndicator();
    }
  }

  updateIndicator() {
    if (!this.navItems) return;
    const index = this.sections.indexOf(this.activeSection);
    if (index >= 0 && this.navItems.length > index) {
      const item = this.navItems.toArray()[index].nativeElement;
      this.indicatorStyle = {
        left: `${item.offsetLeft}px`,
        width: `${item.offsetWidth}px`,
        opacity: 1
      };
    }
  }

  ngOnInit(): void {
    // Initialization logic if needed
  }

  ngAfterViewInit(): void {
    // Initialize indicator position
    setTimeout(() => {
      this.updateIndicator();
    }, 100);
  }


  toggleMobileMenu(): void {
    this.isMobileMenuOpen = !this.isMobileMenuOpen;
  }
}
